---
- name: Include Slurm packages and directories
  ansible.builtin.include_tasks: slurm_packages.yml

- name: Include Slurm binaries
  ansible.builtin.include_tasks: slurm_binaries.yml

- name: Include Slurm certificates
  ansible.builtin.include_tasks: slurm_certs.yml

- name: Include Slurm configuration
  ansible.builtin.include_tasks: slurm_config.yml

- name: Include Slurm services and validation
  ansible.builtin.include_tasks: slurm_services.yml

- name: Include Slurm artifact export
  ansible.builtin.include_tasks: slurm_artifacts.yml
